/**
 * latex-commands - LaTeX 自动补全命令清单
 *
 * 覆盖：KaTeX 常用命令（字母/运算符/关系/箭头/大型运算符/函数/结构/环境/括号）、
 * mhchem（\ce \pu）、项目物理宏表（\dv \ket 等）。
 * template 中第一个 `{}` 或 `[]` 为占位符，插入后光标落在其中（ADR-0005）。
 * hint 为面向不熟悉语法者的中文提示。
 */
export interface LatexCommand {
	/** 命令名（含反斜杠），触发匹配的键 */
	name: string;
	/** 插入模板；第一个 {} 或 [] 是占位符 */
	template: string;
	/** 中文用途提示 */
	hint: string;
}

export const LATEX_COMMANDS: LatexCommand[] = [
	// —— 结构（最高频） ——
	{ name: "\\frac", template: "\\frac{}{}", hint: "分数" },
	{ name: "\\dfrac", template: "\\dfrac{}{}", hint: "分数（ display 尺寸）" },
	{ name: "\\sqrt", template: "\\sqrt{}", hint: "根号" },
	{ name: "\\binom", template: "\\binom{}{}", hint: "二项式系数" },
	{ name: "\\text", template: "\\text{}", hint: "普通文本" },
	{ name: "\\boxed", template: "\\boxed{}", hint: "加框" },
	{ name: "\\overline", template: "\\overline{}", hint: "上横线" },
	{ name: "\\underline", template: "\\underline{}", hint: "下划线" },
	{ name: "\\vec", template: "\\vec{}", hint: "向量箭头" },
	{ name: "\\hat", template: "\\hat{}", hint: "尖帽" },
	{ name: "\\bar", template: "\\bar{}", hint: "短横线" },
	{ name: "\\tilde", template: "\\tilde{}", hint: "波浪号" },
	{ name: "\\dot", template: "\\dot{}", hint: "单点（一阶导）" },
	{ name: "\\ddot", template: "\\ddot{}", hint: "双点（二阶导）" },
	{ name: "\\widehat", template: "\\widehat{}", hint: "宽尖帽" },
	{ name: "\\widetilde", template: "\\widetilde{}", hint: "宽波浪" },
	{ name: "\\overrightarrow", template: "\\overrightarrow{}", hint: "右箭头（向量）" },
	{ name: "\\overbrace", template: "\\overbrace{}", hint: "上花括号" },
	{ name: "\\underbrace", template: "\\underbrace{}", hint: "下花括号" },
	{ name: "\\overset", template: "\\overset{}{}", hint: "上方标注" },
	{ name: "\\underset", template: "\\underset{}{}", hint: "下方标注" },
	{ name: "\\cancel", template: "\\cancel{}", hint: "删除线（约去）" },
	{ name: "\\color", template: "\\color{}", hint: "颜色" },
	// —— 希腊字母 ——
	{ name: "\\alpha", template: "\\alpha", hint: "α" },
	{ name: "\\beta", template: "\\beta", hint: "β" },
	{ name: "\\gamma", template: "\\gamma", hint: "γ" },
	{ name: "\\delta", template: "\\delta", hint: "δ" },
	{ name: "\\epsilon", template: "\\epsilon", hint: "ϵ" },
	{ name: "\\varepsilon", template: "\\varepsilon", hint: "ε（变体）" },
	{ name: "\\zeta", template: "\\zeta", hint: "ζ" },
	{ name: "\\eta", template: "\\eta", hint: "η" },
	{ name: "\\theta", template: "\\theta", hint: "θ" },
	{ name: "\\vartheta", template: "\\vartheta", hint: "ϑ（变体）" },
	{ name: "\\iota", template: "\\iota", hint: "ι" },
	{ name: "\\kappa", template: "\\kappa", hint: "κ" },
	{ name: "\\lambda", template: "\\lambda", hint: "λ" },
	{ name: "\\mu", template: "\\mu", hint: "μ" },
	{ name: "\\nu", template: "\\nu", hint: "ν" },
	{ name: "\\xi", template: "\\xi", hint: "ξ" },
	{ name: "\\pi", template: "\\pi", hint: "π" },
	{ name: "\\varpi", template: "\\varpi", hint: "ϖ（变体）" },
	{ name: "\\rho", template: "\\rho", hint: "ρ" },
	{ name: "\\varrho", template: "\\varrho", hint: "ϱ（变体）" },
	{ name: "\\sigma", template: "\\sigma", hint: "σ" },
	{ name: "\\varsigma", template: "\\varsigma", hint: "ς（变体）" },
	{ name: "\\tau", template: "\\tau", hint: "τ" },
	{ name: "\\upsilon", template: "\\upsilon", hint: "υ" },
	{ name: "\\phi", template: "\\phi", hint: "ϕ" },
	{ name: "\\varphi", template: "\\varphi", hint: "φ（变体）" },
	{ name: "\\chi", template: "\\chi", hint: "χ" },
	{ name: "\\psi", template: "\\psi", hint: "ψ" },
	{ name: "\\omega", template: "\\omega", hint: "ω" },
	{ name: "\\Gamma", template: "\\Gamma", hint: "Γ" },
	{ name: "\\Delta", template: "\\Delta", hint: "Δ" },
	{ name: "\\Theta", template: "\\Theta", hint: "Θ" },
	{ name: "\\Lambda", template: "\\Lambda", hint: "Λ" },
	{ name: "\\Xi", template: "\\Xi", hint: "Ξ" },
	{ name: "\\Pi", template: "\\Pi", hint: "Π" },
	{ name: "\\Sigma", template: "\\Sigma", hint: "Σ" },
	{ name: "\\Upsilon", template: "\\Upsilon", hint: "Υ" },
	{ name: "\\Phi", template: "\\Phi", hint: "Φ" },
	{ name: "\\Psi", template: "\\Psi", hint: "Ψ" },
	{ name: "\\Omega", template: "\\Omega", hint: "Ω" },
	// —— 大型运算符 ——
	{ name: "\\sum", template: "\\sum_{}^{}", hint: "求和" },
	{ name: "\\prod", template: "\\prod_{}^{}", hint: "连乘" },
	{ name: "\\int", template: "\\int_{}^{}", hint: "积分" },
	{ name: "\\iint", template: "\\iint", hint: "二重积分" },
	{ name: "\\iiint", template: "\\iiint", hint: "三重积分" },
	{ name: "\\oint", template: "\\oint_{}^{}", hint: "环路积分" },
	{ name: "\\lim", template: "\\lim_{}", hint: "极限" },
	{ name: "\\bigcup", template: "\\bigcup_{}^{}", hint: "大并集" },
	{ name: "\\bigcap", template: "\\bigcap_{}^{}", hint: "大交集" },
	{ name: "\\bigoplus", template: "\\bigoplus_{}^{}", hint: "大直和" },
	{ name: "\\bigotimes", template: "\\bigotimes_{}^{}", hint: "大张量积" },
	{ name: "\\sup", template: "\\sup", hint: "上确界" },
	{ name: "\\inf", template: "\\inf", hint: "下确界" },
	{ name: "\\max", template: "\\max", hint: "最大值" },
	{ name: "\\min", template: "\\min", hint: "最小值" },
	// —— 函数名 ——
	{ name: "\\sin", template: "\\sin", hint: "正弦" },
	{ name: "\\cos", template: "\\cos", hint: "余弦" },
	{ name: "\\tan", template: "\\tan", hint: "正切" },
	{ name: "\\sec", template: "\\sec", hint: "正割" },
	{ name: "\\csc", template: "\\csc", hint: "余割" },
	{ name: "\\cot", template: "\\cot", hint: "余切" },
	{ name: "\\arcsin", template: "\\arcsin", hint: "反正弦" },
	{ name: "\\arccos", template: "\\arccos", hint: "反余弦" },
	{ name: "\\arctan", template: "\\arctan", hint: "反正切" },
	{ name: "\\sinh", template: "\\sinh", hint: "双曲正弦" },
	{ name: "\\cosh", template: "\\cosh", hint: "双曲余弦" },
	{ name: "\\tanh", template: "\\tanh", hint: "双曲正切" },
	{ name: "\\log", template: "\\log", hint: "对数" },
	{ name: "\\ln", template: "\\ln", hint: "自然对数" },
	{ name: "\\lg", template: "\\lg", hint: "常用对数" },
	{ name: "\\exp", template: "\\exp", hint: "指数" },
	{ name: "\\det", template: "\\det", hint: "行列式" },
	{ name: "\\dim", template: "\\dim", hint: "维数" },
	{ name: "\\ker", template: "\\ker", hint: "核" },
	{ name: "\\deg", template: "\\deg", hint: "度数" },
	{ name: "\\gcd", template: "\\gcd", hint: "最大公约数" },
	{ name: "\\Pr", template: "\\Pr", hint: "概率" },
	// —— 关系符 ——
	{ name: "\\leq", template: "\\leq", hint: "≤" },
	{ name: "\\geq", template: "\\geq", hint: "≥" },
	{ name: "\\neq", template: "\\neq", hint: "≠" },
	{ name: "\\approx", template: "\\approx", hint: "≈" },
	{ name: "\\equiv", template: "\\equiv", hint: "≡" },
	{ name: "\\sim", template: "\\sim", hint: "∼" },
	{ name: "\\simeq", template: "\\simeq", hint: "≃" },
	{ name: "\\cong", template: "\\cong", hint: "≅" },
	{ name: "\\propto", template: "\\propto", hint: "∝ 正比于" },
	{ name: "\\ll", template: "\\ll", hint: "≪ 远小于" },
	{ name: "\\gg", template: "\\gg", hint: "≫ 远大于" },
	{ name: "\\in", template: "\\in", hint: "∈ 属于" },
	{ name: "\\notin", template: "\\notin", hint: "∉ 不属于" },
	{ name: "\\ni", template: "\\ni", hint: "∋ 包含" },
	{ name: "\\subset", template: "\\subset", hint: "⊂" },
	{ name: "\\supset", template: "\\supset", hint: "⊃" },
	{ name: "\\subseteq", template: "\\subseteq", hint: "⊆" },
	{ name: "\\supseteq", template: "\\supseteq", hint: "⊇" },
	{ name: "\\cup", template: "\\cup", hint: "∪ 并" },
	{ name: "\\cap", template: "\\cap", hint: "∩ 交" },
	{ name: "\\setminus", template: "\\setminus", hint: "∖ 差集" },
	{ name: "\\emptyset", template: "\\emptyset", hint: "∅ 空集" },
	{ name: "\\forall", template: "\\forall", hint: "∀ 任意" },
	{ name: "\\exists", template: "\\exists", hint: "∃ 存在" },
	{ name: "\\nexists", template: "\\nexists", hint: "∄ 不存在" },
	{ name: "\\because", template: "\\because", hint: "∵ 因为" },
	{ name: "\\therefore", template: "\\therefore", hint: "∴ 所以" },
	{ name: "\\perp", template: "\\perp", hint: "⊥ 垂直" },
	{ name: "\\parallel", template: "\\parallel", hint: "∥ 平行" },
	{ name: "\\models", template: "\\models", hint: "⊨ 满足" },
	{ name: "\\vdash", template: "\\vdash", hint: "⊢ 推出" },
	{ name: "\\prec", template: "\\prec", hint: "≺" },
	{ name: "\\succ", template: "\\succ", hint: "≻" },
	// —— 二元运算符 ——
	{ name: "\\pm", template: "\\pm", hint: "±" },
	{ name: "\\mp", template: "\\mp", hint: "∓" },
	{ name: "\\times", template: "\\times", hint: "×" },
	{ name: "\\div", template: "\\div", hint: "÷" },
	{ name: "\\cdot", template: "\\cdot", hint: "⋅ 点乘" },
	{ name: "\\ast", template: "\\ast", hint: "∗" },
	{ name: "\\star", template: "\\star", hint: "⋆" },
	{ name: "\\circ", template: "\\circ", hint: "∘ 复合" },
	{ name: "\\bullet", template: "\\bullet", hint: "∙" },
	{ name: "\\oplus", template: "\\oplus", hint: "⊕ 直和" },
	{ name: "\\ominus", template: "\\ominus", hint: "⊖" },
	{ name: "\\otimes", template: "\\otimes", hint: "⊗ 张量积" },
	{ name: "\\odot", template: "\\odot", hint: "⊙" },
	{ name: "\\wedge", template: "\\wedge", hint: "∧ 与/外积" },
	{ name: "\\vee", template: "\\vee", hint: "∨ 或" },
	{ name: "\\triangleq", template: "\\triangleq", hint: "≜ 定义为" },
	// —— 箭头 ——
	{ name: "\\to", template: "\\to", hint: "→" },
	{ name: "\\rightarrow", template: "\\rightarrow", hint: "→" },
	{ name: "\\leftarrow", template: "\\leftarrow", hint: "←" },
	{ name: "\\Rightarrow", template: "\\Rightarrow", hint: "⇒" },
	{ name: "\\Leftarrow", template: "\\Leftarrow", hint: "⇐" },
	{ name: "\\leftrightarrow", template: "\\leftrightarrow", hint: "↔" },
	{ name: "\\Leftrightarrow", template: "\\Leftrightarrow", hint: "⇔" },
	{ name: "\\mapsto", template: "\\mapsto", hint: "↦ 映射到" },
	{ name: "\\implies", template: "\\implies", hint: "⟹ 推出" },
	{ name: "\\impliedby", template: "\\impliedby", hint: "⟸ 被推出" },
	{ name: "\\iff", template: "\\iff", hint: "⟺ 当且仅当" },
	{ name: "\\uparrow", template: "\\uparrow", hint: "↑" },
	{ name: "\\downarrow", template: "\\downarrow", hint: "↓" },
	{ name: "\\nearrow", template: "\\nearrow", hint: "↗" },
	{ name: "\\searrow", template: "\\searrow", hint: "↘" },
	{ name: "\\xrightarrow", template: "\\xrightarrow[]{}", hint: "带字右箭头（下上标注）" },
	{ name: "\\xleftarrow", template: "\\xleftarrow[]{}", hint: "带字左箭头（下上标注）" },
	// —— 省略号与杂项符号 ——
	{ name: "\\dots", template: "\\dots", hint: "… 智能省略号" },
	{ name: "\\ldots", template: "\\ldots", hint: "… 下排省略号" },
	{ name: "\\cdots", template: "\\cdots", hint: "⋯ 中排省略号" },
	{ name: "\\vdots", template: "\\vdots", hint: "⋮ 竖省略号" },
	{ name: "\\ddots", template: "\\ddots", hint: "⋱ 斜省略号" },
	{ name: "\\infty", template: "\\infty", hint: "∞ 无穷" },
	{ name: "\\partial", template: "\\partial", hint: "∂ 偏微分" },
	{ name: "\\nabla", template: "\\nabla", hint: "∇ 梯度算子" },
	{ name: "\\hbar", template: "\\hbar", hint: "ℏ 约化普朗克常量" },
	{ name: "\\ell", template: "\\ell", hint: "ℓ" },
	{ name: "\\Re", template: "\\Re", hint: "ℜ 实部" },
	{ name: "\\Im", template: "\\Im", hint: "ℑ 虚部" },
	{ name: "\\aleph", template: "\\aleph", hint: "ℵ" },
	{ name: "\\wp", template: "\\wp", hint: "℘" },
	{ name: "\\prime", template: "\\prime", hint: "′ 撇" },
	{ name: "\\angle", template: "\\angle", hint: "∠ 角" },
	{ name: "\\measuredangle", template: "\\measuredangle", hint: "∡ 有向角" },
	{ name: "\\triangle", template: "\\triangle", hint: "△" },
	{ name: "\\square", template: "\\square", hint: "□" },
	{ name: "\\blacksquare", template: "\\blacksquare", hint: "■ 证毕" },
	{ name: "\\S", template: "\\S", hint: "§ 节符号" },
	{ name: "\\P", template: "\\P", hint: "¶ 段符号" },
	{ name: "\\dag", template: "\\dag", hint: "†" },
	{ name: "\\ddag", template: "\\ddag", hint: "‡" },
	// —— 括号（自动缩放族） ——
	{ name: "\\langle", template: "\\langle", hint: "⟨ 左尖括号" },
	{ name: "\\rangle", template: "\\rangle", hint: "⟩ 右尖括号" },
	{ name: "\\lceil", template: "\\lceil", hint: "⌈ 上取整左" },
	{ name: "\\rceil", template: "\\rceil", hint: "⌉ 上取整右" },
	{ name: "\\lfloor", template: "\\lfloor", hint: "⌊ 下取整左" },
	{ name: "\\rfloor", template: "\\rfloor", hint: "⌋ 下取整右" },
	// —— 字体 ——
	{ name: "\\mathrm", template: "\\mathrm{}", hint: "正体" },
	{ name: "\\mathbf", template: "\\mathbf{}", hint: "粗体" },
	{ name: "\\mathit", template: "\\mathit{}", hint: "斜体" },
	{ name: "\\mathbb", template: "\\mathbb{}", hint: "黑板粗体（数集）" },
	{ name: "\\mathcal", template: "\\mathcal{}", hint: "花体" },
	{ name: "\\mathfrak", template: "\\mathfrak{}", hint: "德文尖角体" },
	{ name: "\\boldsymbol", template: "\\boldsymbol{}", hint: "粗斜体（向量）" },
	// —— 间距 ——
	{ name: "\\quad", template: "\\quad", hint: "大空格" },
	{ name: "\\qquad", template: "\\qquad", hint: "特大空格" },
	{ name: "\\,", template: "\\,", hint: "小空格" },
	{ name: "\\;", template: "\\;", hint: "中空格" },
	{ name: "\\!", template: "\\!", hint: "负空格" },
	// —— 矩阵与环境 ——
	{ name: "\\begin{matrix}", template: "\\begin{matrix}  \\end{matrix}", hint: "矩阵（无括号）" },
	{
		name: "\\begin{pmatrix}",
		template: "\\begin{pmatrix}  \\end{pmatrix}",
		hint: "矩阵（圆括号）",
	},
	{
		name: "\\begin{bmatrix}",
		template: "\\begin{bmatrix}  \\end{bmatrix}",
		hint: "矩阵（方括号）",
	},
	{
		name: "\\begin{Bmatrix}",
		template: "\\begin{Bmatrix}  \\end{Bmatrix}",
		hint: "矩阵（花括号）",
	},
	{ name: "\\begin{vmatrix}", template: "\\begin{vmatrix}  \\end{vmatrix}", hint: "行列式" },
	{ name: "\\begin{cases}", template: "\\begin{cases}  \\end{cases}", hint: "分段函数" },
	{ name: "\\begin{aligned}", template: "\\begin{aligned}  \\end{aligned}", hint: "多行对齐" },
	// —— mhchem ——
	{ name: "\\ce", template: "\\ce{}", hint: "化学式（mhchem）" },
	{ name: "\\pu", template: "\\pu{}", hint: "物理单位（mhchem）" },
	// —— 物理宏表（项目内置） ——
	{ name: "\\dv", template: "\\dv{}{}", hint: "导数 df/dx" },
	{ name: "\\pdv", template: "\\pdv{}{}", hint: "偏导 ∂f/∂x" },
	{ name: "\\dd", template: "\\dd", hint: "微分号 d" },
	{ name: "\\bra", template: "\\bra{}", hint: "⟨ψ|" },
	{ name: "\\ket", template: "\\ket{}", hint: "|ψ⟩" },
	{ name: "\\braket", template: "\\braket{}", hint: "⟨ψ|φ⟩" },
	{ name: "\\expval", template: "\\expval{}", hint: "⟨A⟩ 期望值" },
	{ name: "\\abs", template: "\\abs{}", hint: "|x| 绝对值" },
	{ name: "\\norm", template: "\\norm{}", hint: "‖x‖ 范数" },
	{ name: "\\vu", template: "\\vu{}", hint: "单位向量帽" },
	{ name: "\\grad", template: "\\grad", hint: "∇ 梯度" },
	{ name: "\\divg", template: "\\divg", hint: "∇⋅ 散度" },
	{ name: "\\curl", template: "\\curl", hint: "∇× 旋度" },
	{ name: "\\qty", template: "\\qty{}", hint: "自动缩放圆括号" },
	{ name: "\\RR", template: "\\RR", hint: "ℝ 实数集" },
	{ name: "\\ZZ", template: "\\ZZ", hint: "ℤ 整数集" },
	{ name: "\\NN", template: "\\NN", hint: "ℕ 自然数集" },
	{ name: "\\QQ", template: "\\QQ", hint: "ℚ 有理数集" },
	{ name: "\\CC", template: "\\CC", hint: "ℂ 复数集" },
];
