// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/VOD-Studio/mimo-music/config"
	"github.com/VOD-Studio/mimo-music/internal/server"
	"github.com/VOD-Studio/mimo-music/internal/server/handler"
	"github.com/VOD-Studio/mimo-music/observability"
	"github.com/VOD-Studio/mimo-music/service"
)

// Injectors from wire_injectors.go:

// InitializeServer 用 wire 装配 HTTP 服务组件。
func InitializeServer(cfg config.Config) (*ServerApp, error) {
	logger := ProvideLogger()
	client := ProvideNeteaseClient(cfg, logger)
	auth := ProvideAuth(client)
	redisClient, err := ProvideRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	sessionStore := ProvideSessionStore(redisClient)
	providerSessionStore := ProvideProviderSessionStore(sessionStore)
	authService := service.NewAuthService(auth, providerSessionStore, logger)
	playlist := ProvidePlaylist(client)
	cache := ProvideCache(redisClient)
	providerCache := ProvideProviderCache(cache)
	metrics := observability.NewMetrics()
	playlistService := service.NewPlaylistService(playlist, providerCache, logger, metrics)
	song := ProvideSong(client)
	songService := service.NewSongService(song, providerCache, logger, metrics)
	search := ProvideSearch(client)
	searchService := service.NewSearchService(search, providerCache, logger, metrics)
	album := ProvideAlbum(client)
	albumService := service.NewAlbumService(album, providerCache, logger, metrics)
	artist := ProvideArtist(client)
	artistService := service.NewArtistService(artist, providerCache, logger, metrics)
	recommend := ProvideRecommend(client)
	availabilityStore := ProvideAvailabilityStore(redisClient)
	sessionRotator := ProvideSessionRotator(sessionStore, availabilityStore)
	recommendService := service.NewRecommendService(recommend, sessionRotator, providerCache, logger, metrics)
	fm := ProvideFM(client)
	fmService := service.NewFMService(fm, sessionRotator, providerCache, logger, metrics)
	handlerHandler := handler.New(authService, playlistService, songService, searchService, albumService, artistService, recommendService, fmService)
	httpHandler := server.NewRouter(handlerHandler, metrics)
	serverApp := NewServerApp(httpHandler, redisClient)
	return serverApp, nil
}
