import { readFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const sourceRoot = resolve(packageRoot, "src");
export const repositoryRoot = resolve(packageRoot, "../../..");
export const manifest = JSON.parse(readFileSync(resolve(packageRoot, "component-manifest.json"), "utf8"));

export const moduleName = (entry) => entry.replace(/^src\//, "").replace(/\.[cm]?[jt]sx?$/, "");
export const importPath = (entry) => `./${moduleName(entry)}`;
export const distEntry = (entry, extension = "js") => `./dist/${moduleName(entry)}.${extension}`;

export const publicEntries = [
	{ name: ".", entry: "src/index.ts" },
	{ name: "legacy", entry: "src/legacy.ts" },
	{ name: "variants", entry: "src/variants.ts" },
	...manifest.components,
	...manifest.additionalExports,
];

export function validateManifest() {
	if (manifest.schemaVersion !== 1 || manifest.package !== "@violet/ui") {
		throw new Error("Unsupported @violet/ui component manifest.");
	}
	const names = new Set();
	for (const component of [...manifest.components, ...manifest.additionalExports]) {
		if (!/^[a-z][a-z0-9-]*$/.test(component.name) || names.has(component.name)) {
			throw new Error(`Invalid or duplicate public entry: ${component.name}`);
		}
		names.add(component.name);
		if (!["foundation", "legacy"].includes(component.status)) {
			throw new Error(`Invalid maturity status: ${component.name}`);
		}
		for (const path of [component.entry, component.css].filter(Boolean)) {
			if (!path.startsWith("src/") || path.includes("..") || resolve(packageRoot, path) === sourceRoot) {
				throw new Error(`Entry must be inside src/: ${path}`);
			}
		}
	}
}

export function generatedSources() {
	const header = "// Generated by pnpm sync; edit component-manifest.json instead.\n";
	const exportEntry = ({ entry, symbols }) =>
		symbols
			? `export { ${symbols.join(", ")} } from "${importPath(entry)}";`
			: `export * from "${importPath(entry)}";`;
	const cssImport = (path, layer) =>
		`@import "./${relative(sourceRoot, resolve(packageRoot, path)).replaceAll("\\", "/")}"${layer ? ` layer(${layer})` : ""};`;
	return new Map([
		[
			"src/index.ts",
			`${header}${manifest.components.filter((item) => item.status === "foundation").map(exportEntry).join("\n")}\nexport * from "./legacy";\n`,
		],
		[
			"src/legacy.ts",
			`${header}${[...manifest.components.filter((item) => item.status === "legacy"), ...manifest.additionalExports].map(exportEntry).join("\n")}\n`,
		],
		["src/variants.ts", `${header}${manifest.recipes.map(exportEntry).join("\n")}\n`],
		[
			"src/classes.css",
			`/* Generated by pnpm sync; component CSS is maintained beside its implementation. */\n${manifest.components.filter((item) => item.css).map((item) => cssImport(item.css, item.status === "legacy" ? "components" : undefined)).join("\n")}\n`,
		],
		[
			"src/tokens.css",
			`/* Pure CSS variables; no Tailwind directives or reset. */\n@layer theme, base, components, utilities;\n${[manifest.styles.tokens, manifest.styles.palettes[0], manifest.styles.foundation].map((path) => cssImport(path)).join("\n")}\n`,
		],
		[
			"src/styles.css",
			`/* Import after tailwindcss; site dialects remain in the consuming application. */\n${[manifest.styles.theme, manifest.styles.tokens, manifest.styles.foundation, ...manifest.styles.utilities, manifest.styles.palettes[0]].map((path) => cssImport(path)).join("\n")}\n@import "./classes.css";\n\n/* Legacy components still use complete Tailwind utilities. */\n@source "./";\n`,
		],
	]);
}

export function generatedPackageFields() {
	const sourceExports = {};
	const distExports = {};
	for (const { name, entry } of publicEntries) {
		const key = name === "." ? "." : `./${name}`;
		sourceExports[key] = { types: `./${entry}`, import: `./${entry}`, default: `./${entry}` };
		distExports[key] = { types: distEntry(entry, "d.ts"), import: distEntry(entry), default: distEntry(entry) };
	}
	for (const name of ["styles", "tokens", "classes"]) {
		sourceExports[`./${name}.css`] = `./src/${name}.css`;
		distExports[`./${name}.css`] = `./dist/${name}.css`;
	}
	for (const { name, css } of manifest.components.filter((item) => item.css)) {
		sourceExports[`./components/${name}.css`] = `./${css}`;
		distExports[`./components/${name}.css`] = `./dist/components/${name}.css`;
	}
	for (const palette of manifest.styles.palettes) {
		const name = palette.split("/").at(-1);
		sourceExports[`./palettes/${name}`] = `./${palette}`;
		distExports[`./palettes/${name}`] = `./dist/palettes/${name}`;
	}
	sourceExports["./component-manifest.json"] = "./component-manifest.json";
	distExports["./component-manifest.json"] = "./component-manifest.json";
	sourceExports["./package.json"] = "./package.json";
	distExports["./package.json"] = "./package.json";
	return { sourceExports, distExports };
}

export const cssEntries = {
	styles: "src/styles.css",
	tokens: "src/tokens.css",
	classes: "src/classes.css",
	...Object.fromEntries(manifest.components.filter((item) => item.css).map((item) => [`components/${item.name}`, item.css])),
	...Object.fromEntries(manifest.styles.palettes.map((path) => [`palettes/${path.split("/").at(-1).replace(/\.css$/, "")}`, path])),
};
