// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	command3 "blog-api/internal/application/permission/command"
	query2 "blog-api/internal/application/permission/query"
	command2 "blog-api/internal/application/role/command"
	"blog-api/internal/application/role/query"
	"blog-api/internal/application/shared"
	"blog-api/internal/domain/permission"
	role2 "blog-api/internal/domain/role"
	"blog-api/internal/infrastructure/eventbus"
	gorm2 "blog-api/internal/infrastructure/persistence/gorm"
	"blog-api/internal/interfaces/http/handler/role"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// InitializeRoleContainer 装配 role/permission 模块依赖图
func InitializeRoleContainer(db *gorm.DB) (*RoleContainer, func(), error) {
	roleRepository := gorm2.NewRoleRepository(db)
	listRolesWithUserCountHandler := query.NewListRolesWithUserCountHandler(roleRepository)
	permissionRepository := gorm2.NewPermissionRepository(db)
	getRoleWithPermissionsHandler := query.NewGetRoleWithPermissionsHandler(roleRepository, permissionRepository)
	inMemory := eventbus.NewInMemory()
	createRoleHandler := command2.NewCreateRoleHandler(roleRepository, inMemory)
	updateRoleHandler := command2.NewUpdateRoleHandler(roleRepository)
	deleteRoleHandler := command2.NewDeleteRoleHandler(roleRepository)
	replaceRolePermissionsHandler := command2.NewReplaceRolePermissionsHandler(roleRepository, inMemory)
	listPermissionsHandler := query2.NewListPermissionsHandler(permissionRepository)
	createPermissionHandler := command3.NewCreatePermissionHandler(permissionRepository)
	updatePermissionHandler := command3.NewUpdatePermissionHandler(permissionRepository)
	deletePermissionHandler := command3.NewDeletePermissionHandler(permissionRepository)
	handler := role.NewHandler(listRolesWithUserCountHandler, getRoleWithPermissionsHandler, createRoleHandler, updateRoleHandler, deleteRoleHandler, replaceRolePermissionsHandler, listPermissionsHandler, createPermissionHandler, updatePermissionHandler, deletePermissionHandler)
	roleContainer := newRoleContainer(handler)
	return roleContainer, func() {
	}, nil
}

// wire.go:

// InfrastructureSet 基础设施层
var InfrastructureSet = wire.NewSet(eventbus.NewInMemory, wire.Bind(new(shared.EventBus), new(*eventbus.InMemory)))

// RoleDomainSet role/permission 聚合 repository
var RoleDomainSet = wire.NewSet(gorm2.NewRoleRepository, wire.Bind(new(role2.RoleRepository), new(*gorm2.RoleRepository)), gorm2.NewPermissionRepository, wire.Bind(new(permission.PermissionRepository), new(*gorm2.PermissionRepository)))

// RoleApplicationSet role/permission 用例层（CQRS）
var RoleApplicationSet = wire.NewSet(command2.NewCreateRoleHandler, command2.NewUpdateRoleHandler, command2.NewDeleteRoleHandler, command2.NewReplaceRolePermissionsHandler, query.NewListRolesWithUserCountHandler, query.NewGetRoleWithPermissionsHandler, command3.NewCreatePermissionHandler, command3.NewUpdatePermissionHandler, command3.NewDeletePermissionHandler, query2.NewListPermissionsHandler)

// RoleInterfacesSet role/permission HTTP handler
var RoleInterfacesSet = wire.NewSet(role.NewHandler)

// RoleContainer role/permission 模块容器
type RoleContainer struct {
	RoleHandler *role.Handler
}

func newRoleContainer(roleHandler *role.Handler) *RoleContainer {
	return &RoleContainer{RoleHandler: roleHandler}
}
