// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	permission2 "blog-api/internal/application/permission"
	command2 "blog-api/internal/application/permission/command"
	query2 "blog-api/internal/application/permission/query"
	"blog-api/internal/application/role/command"
	"blog-api/internal/application/role/query"
	"blog-api/internal/application/shared"
	"blog-api/internal/domain/permission"
	role2 "blog-api/internal/domain/role"
	"blog-api/internal/infrastructure/eventbus"
	gorm2 "blog-api/internal/infrastructure/persistence/gorm"
	"blog-api/internal/interfaces/http/handler/role"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeRoleContainer 装配 role/permission 模块依赖图
func InitializeRoleContainer(db *gorm.DB) (*RoleContainer, func(), error) {
	roleRepository := gorm2.NewRoleRepository(db)
	listRolesWithUserCountHandler := query.NewListRolesWithUserCountHandler(roleRepository)
	permissionRepository := gorm2.NewPermissionRepository(db)
	getRoleWithPermissionsHandler := query.NewGetRoleWithPermissionsHandler(roleRepository, permissionRepository)
	inMemory := eventbus.NewInMemory()
	createRoleHandler := command.NewCreateRoleHandler(roleRepository, inMemory)
	updateRoleHandler := command.NewUpdateRoleHandler(roleRepository)
	deleteRoleHandler := command.NewDeleteRoleHandler(roleRepository)
	replaceRolePermissionsHandler := command.NewReplaceRolePermissionsHandler(roleRepository, inMemory)
	listPermissionsHandler := query2.NewListPermissionsHandler(permissionRepository)
	createPermissionHandler := command2.NewCreatePermissionHandler(permissionRepository)
	updatePermissionHandler := command2.NewUpdatePermissionHandler(permissionRepository)
	deletePermissionHandler := command2.NewDeletePermissionHandler(permissionRepository)
	handler := role.NewHandler(listRolesWithUserCountHandler, getRoleWithPermissionsHandler, createRoleHandler, updateRoleHandler, deleteRoleHandler, replaceRolePermissionsHandler, listPermissionsHandler, createPermissionHandler, updatePermissionHandler, deletePermissionHandler)
	checker := NewPermissionCheckerWithSubscription(roleRepository, inMemory)
	roleContainer := newRoleContainer(handler, checker)
	return roleContainer, func() {
	}, nil
}

// wire.go:

// InfrastructureSet 基础设施层
var InfrastructureSet = wire.NewSet(eventbus.NewInMemory, wire.Bind(new(shared.EventBus), new(*eventbus.InMemory)))

// RoleDomainSet role/permission 聚合 repository
var RoleDomainSet = wire.NewSet(gorm2.NewRoleRepository, wire.Bind(new(role2.RoleRepository), new(*gorm2.RoleRepository)), gorm2.NewPermissionRepository, wire.Bind(new(permission.PermissionRepository), new(*gorm2.PermissionRepository)))

// RoleApplicationSet role/permission 用例层（CQRS）
var RoleApplicationSet = wire.NewSet(command.NewCreateRoleHandler, command.NewUpdateRoleHandler, command.NewDeleteRoleHandler, command.NewReplaceRolePermissionsHandler, query.NewListRolesWithUserCountHandler, query.NewGetRoleWithPermissionsHandler, command2.NewCreatePermissionHandler, command2.NewUpdatePermissionHandler, command2.NewDeletePermissionHandler, query2.NewListPermissionsHandler)

// RoleInterfacesSet role/permission HTTP handler
var RoleInterfacesSet = wire.NewSet(role.NewHandler)

// PermissionCheckerSet 运行时权限检查器装配
//
// NewPermissionCheckerWithSubscription 是 *appperm.Checker 的唯一 provider，
// 内部同时完成构造与事件订阅注册。它依赖 wire 单例 *InMemory——
// 该单例同时被 RoleApplicationSet 注入给 ReplaceRolePermissionsHandler，
// 因此订阅方与发布方共享同一总线实例，事件链在此闭合。
var PermissionCheckerSet = wire.NewSet(
	NewPermissionCheckerWithSubscription,
)

// RoleContainer role/permission 模块容器
type RoleContainer struct {
	RoleHandler       *role.Handler
	PermissionChecker *permission2.Checker
}

func newRoleContainer(roleHandler *role.Handler, checker *permission2.Checker) *RoleContainer {
	return &RoleContainer{RoleHandler: roleHandler, PermissionChecker: checker}
}
