// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"blog-api/internal/application/shared"
	"blog-api/internal/application/user/command"
	user2 "blog-api/internal/domain/user"
	"blog-api/internal/infrastructure/eventbus"
	gorm2 "blog-api/internal/infrastructure/persistence/gorm"
	"blog-api/internal/interfaces/http/handler/user"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeUserContainer 装配 user 模块依赖图
//
// 参数 db 由 main.go 注入（已配置连接池、已执行迁移）。
// wire 据此自动生成依赖图，编译期校验完整性。
func InitializeUserContainer(db *gorm.DB) (*UserContainer, func(), error) {
	userRepository := gorm2.NewUserRepository(db)
	inMemory := eventbus.NewInMemory()
	bcryptHasher := command.NewBcryptHasher()
	registerUserHandler := command.NewRegisterUserHandler(userRepository, inMemory, bcryptHasher)
	handler := user.NewHandler(registerUserHandler)
	userContainer := newUserContainer(registerUserHandler, handler)
	return userContainer, func() {
	}, nil
}

// wire.go:

// InfrastructureSet 基础设施层 provider 集合
//
// 提供 GORM repository、事件总线、密码哈希器等基础设施实现。
// 注意：*gorm.DB 由 main.go 现有代码初始化后注入（wire 不负责创建 DB 连接，
// 因为连接池配置、ping、迁移都在 main.go 中执行）。
var InfrastructureSet = wire.NewSet(eventbus.NewInMemory, wire.Bind(new(shared.EventBus), new(*eventbus.InMemory)), command.NewBcryptHasher, wire.Bind(new(command.PasswordHasher), new(*command.BcryptHasher)))

// UserDomainSet user 聚合的 repository provider
//
// *gorm.DB 由调用方（main.go）注入，wire 在此绑定接口实现。
var UserDomainSet = wire.NewSet(gorm2.NewUserRepository, wire.Bind(new(user2.UserRepository), new(*gorm2.UserRepository)))

// UserApplicationSet user 聚合的 application 层（用例）provider
var UserApplicationSet = wire.NewSet(command.NewRegisterUserHandler)

// UserInterfacesSet user 聚合的 interfaces 层（HTTP handler）provider
var UserInterfacesSet = wire.NewSet(user.NewHandler)

// UserContainer user 模块依赖容器
//
// 聚合 user 模块的所有依赖（repository、用例、handler），
// 由 main.go 通过 InitializeUserContainer 获取后注册路由。
type UserContainer struct {
	RegisterHandler *command.RegisterUserHandler
	UserHandler     *user.Handler
}

// newUserContainer 构造容器（wire 使用）
func newUserContainer(
	registerHandler *command.RegisterUserHandler,
	userHandler *user.Handler,
) *UserContainer {
	return &UserContainer{
		RegisterHandler: registerHandler,
		UserHandler:     userHandler,
	}
}
