import type { EmotionDef } from "./types";

export const EMOTIONS: EmotionDef[] = [
	// ==================== 1）生命周期 (00-07) ====================
	{
		id: "00",
		name: "待机",
		en: "Idle",
		group: "lifecycle",
		desc: "软糯团子从容地左看看右看看，尾巴轻摇，耳朵偶尔灵动微颤。",
		transition: 700,
		pool: ["round", "flat"],
		poolMs: [9000, 16000],
		blinkMs: [6000, 14000],
		antics: true,
		body: { breathe: 0.012, earL: 0, earR: 0, tail: 0.5, tailElev: 0.3, mouth: "w" },
		anims: [
			{ type: "glance", target: "eyes", prop: "lookX", amp: 10, period: 4800 },
			{ type: "sine", target: "eyes", prop: "lookY", amp: 2, period: 4100, phase: 1.1 },
		],
	},
	{
		id: "01",
		name: "睡眠",
		en: "Sleep",
		group: "lifecycle",
		desc: "耳朵耷拉，闭眼成细线，右上角 zzz 缓缓飘起，均匀呼呼。",
		transition: 900,
		gaze: false,
		pool: ["slit", "droop", "flat"],
		poolMs: [6000, 10000],
		blinkMs: null,
		openness: 0.08,
		body: {
			y: 4,
			rotate: -2,
			breathe: 0.018,
			color: "#E9E5F5",
			zzz: 1,
			earL: -10,
			earR: 10,
			tail: 0.1,
			tailElev: -0.5,
			mouth: "w",
			mouthScale: 0.8,
		},
		eyes: { both: { y: 4, lookY: 2 } },
		anims: [{ type: "sine", target: "eyes", prop: "y", amp: 1.2, period: 3600 }],
	},
	{
		id: "02",
		name: "唤醒",
		en: "Wake",
		group: "lifecycle",
		desc: "耳朵从下耷抖抖立起，双眼交错揉揉睁开，随后进入待机。",
		transition: 320,
		pool: ["slit"],
		poolMs: [800, 800],
		blinkMs: null,
		body: { breathe: 0.012, mouth: "w" },
		sequence: {
			settle: { next: "00" },
			frames: [
				{
					at: 0,
					body: { earL: -12, earR: 12, mouth: "o", mouthScale: 0.8 },
					eyes: { both: { open: 0.1, y: 4 } },
				},
				{
					at: 420,
					body: { earL: 4, earR: 10, mouth: "o", mouthScale: 1.1 },
					eyes: { left: { open: 0.55, y: 2 }, right: { open: 0.12, y: 4 } },
				},
				{
					at: 820,
					body: { earL: -2, earR: 4, mouth: "w" },
					eyes: { both: { open: 0.3, y: 3 } },
				},
				{
					at: 1400,
					body: { earL: 8, earR: -8, mouth: "smile" },
					eyes: { both: { open: 1, scaleX: 1.12, scaleY: 1.12, y: -2 } },
				},
				{
					at: 2100,
					body: { earL: 0, earR: 0, mouth: "w" },
					eyes: { both: { open: 1, y: 0 } },
				},
			],
		},
	},
	{
		id: "03",
		name: "待命",
		en: "Standby",
		group: "lifecycle",
		desc: "猫耳轻趴半开合，几乎静止，只剩极微弱的呼吸。",
		transition: 1200,
		gaze: false,
		pool: ["droop", "flat", "slit"],
		poolMs: [4000, 8000],
		blinkMs: null,
		openness: 0.4,
		body: {
			y: 5,
			scale: 0.98,
			rotate: -1,
			breathe: 0.005,
			color: "#E0DBEC",
			earL: -8,
			earR: 8,
			tail: 0.1,
			tailElev: -0.4,
			mouth: "flat",
		},
		eyes: { both: { y: 4 } },
	},
	{
		id: "04",
		name: "伸懒腰",
		en: "Yawn & Stretch",
		group: "lifecycle",
		desc: "大打哈欠，身体舒展拉长，小爪爪前伸，随后满足地抖抖耳朵。",
		transition: 360,
		pool: ["slit", "droop"],
		poolMs: [2000, 4000],
		blinkMs: null,
		body: { breathe: 0.01, mouth: "open", tailElev: 0.8 },
		sequence: {
			settle: "base",
			frames: [
				{ at: 0, body: { y: 0, scale: 1, earL: 0, earR: 0, mouth: "w" } },
				{
					at: 450,
					body: {
						y: -8,
						scale: 1.08,
						earL: -16,
						earR: 16,
						tail: 1,
						tailElev: 0.9,
						mouth: "open",
						pawL: { x: -6, y: 10, scale: 1.1 },
						pawR: { x: 6, y: 10, scale: 1.1 },
					},
					eyes: { both: { scaleY: 0.2, y: -4 } },
				},
				{
					at: 1100,
					body: {
						y: -10,
						scale: 1.06,
						earL: -14,
						earR: 14,
						tail: 0.9,
						tailElev: 0.8,
						mouth: "open",
						pawL: { x: -4, y: 8, scale: 1.05 },
						pawR: { x: 4, y: 8, scale: 1.05 },
					},
				},
				{
					at: 1800,
					body: {
						y: 0,
						scale: 1,
						earL: 4,
						earR: -4,
						tail: 0.5,
						tailElev: 0.3,
						mouth: "w",
					},
				},
			],
		},
	},
	{
		id: "05",
		name: "好奇探头",
		en: "Curious",
		group: "lifecycle",
		desc: "两耳警觉竖起微偏，小脑袋探出歪歪打量。",
		transition: 420,
		pool: ["wide", "round", "scan"],
		poolMs: [1800, 3200],
		blinkMs: [2500, 5500],
		body: {
			rotate: 6,
			breathe: 0.01,
			earL: 12,
			earR: -4,
			tail: 0.8,
			tailElev: 0.6,
			mouth: "w",
			pawL: { y: -8, rotate: -6 },
		},
		eyes: { both: { lookY: -1 } },
		anims: [{ type: "sine", target: "eyes", prop: "lookX", amp: 2.4, period: 2800 }],
	},
	{
		id: "06",
		name: "摸鱼发呆",
		en: "Spacing Out",
		group: "lifecycle",
		desc: "半睁着眼放空，双眼焦点各游各的，耳朵无意识地轻微抽动。",
		transition: 800,
		pool: ["flat", "droop", "round"],
		poolMs: [3500, 6000],
		blinkMs: [4000, 8000],
		antics: true,
		body: {
			rotate: -3,
			breathe: 0.008,
			earL: 4,
			earR: 8,
			tail: 0.2,
			tailElev: 0.1,
			mouth: "flat",
		},
		eyes: {
			left: { lookX: -4, lookY: 2 },
			right: { lookX: 5, lookY: -1 },
		},
		anims: [{ type: "sine", target: "eyes", prop: "lookX", amp: 3, period: 6800 }],
	},
	{
		id: "07",
		name: "启动自检",
		en: "Booting",
		group: "lifecycle",
		desc: "双眼与双耳交替律动闪烁，如同猫咪核心模块逐项唤醒初始化。",
		transition: 480,
		pool: ["round", "dot"],
		poolMs: [6000, 10000],
		blinkMs: null,
		body: { earL: 2, earR: -2, mouth: "o", mouthScale: 0.9 },
		anims: [
			{ type: "blink", target: "left", prop: "open", period: 1600, dur: 700 },
			{ type: "blink", target: "right", prop: "open", period: 1600, dur: 700, phaseMs: 800 },
			{ type: "pulse", target: "eyes", prop: "scale", amp: 0.04, period: 1600 },
		],
	},

	// ==================== 2）情绪反应 (10-26) ====================
	{
		id: "08",
		name: "Ciallo～",
		en: "Ciallo",
		group: "emotion",
		desc: "Ciallo～(∠・ω< )⌒★! 经典的 Wink 眨眼与额角招手元气问候！",
		transition: 260,
		pair: ["sparkle", "wink"],
		pool: ["sparkle", "wink"],
		poolMs: [4000, 8000],
		blinkMs: null,
		confetti: 22,
		body: {
			rotate: 7,
			y: -3,
			earL: 14,
			earR: -16,
			tail: 0.95,
			tailElev: 0.9,
			blush: 0.85,
			mouth: "w",
			pawL: { y: 2, x: -4, rotate: 12 },
			pawR: { y: -82, x: 20, rotate: -48, scale: 1.25 },
		},
		eyes: { left: { scaleX: 1.15, scaleY: 1.15, y: -1 }, right: { scaleY: 0.95, y: 1 } },
		anims: [
			{ type: "sine", target: "body", prop: "rotate", amp: 2.2, period: 1800 },
			{ type: "pulse", target: "eyes", prop: "scale", amp: 0.08, period: 1200 },
			{ type: "sine", target: "right", prop: "pawRY", amp: 3, period: 1400 },
		],
	},
	{
		id: "09",
		name: "开心",
		en: "Happy",
		group: "emotion",
		desc: "笑眼弯弯，双耳愉快轻颤，小尾巴欢快摇摆。",
		transition: 380,
		pool: ["smile", "grin", "smile"],
		poolMs: [2500, 4500],
		blinkMs: [2500, 5000],
		antics: true,
		body: {
			y: -3,
			breathe: 0.014,
			earL: 6,
			earR: -6,
			tail: 0.9,
			tailElev: 0.7,
			blush: 0.5,
			mouth: "smile",
		},
		eyes: { both: { y: -3 } },
		anims: [
			{ type: "glance", target: "eyes", prop: "lookY", amp: 6, period: 3000 },
			{ type: "sine", target: "body", prop: "y", amp: 2.2, period: 1400 },
		],
	},
	{
		id: "10",
		name: "狂喜大笑",
		en: "Laughing",
		group: "emotion",
		desc: "笑到眯缝，两只小爪爪兴奋抓动，开心地弹起庆祝！",
		transition: 240,
		pool: ["grin"],
		poolMs: [4000, 8000],
		blinkMs: null,
		spin: 1,
		confetti: 0.7,
		body: {
			breathe: 0.012,
			earL: 10,
			earR: -10,
			tail: 1,
			tailElev: 0.9,
			blush: 0.65,
			mouth: "open",
		},
		eyes: { both: { y: -3 } },
		anims: [{ type: "pulse", target: "body", prop: "scale", amp: 0.04, period: 900 }],
		sequence: {
			settle: "base",
			frames: [
				{ at: 0, body: { y: 0 } },
				{
					at: 300,
					eyes: { both: { scaleX: 1.1, scaleY: 1.1, y: -5 } },
					body: {
						y: -6,
						pawL: { y: -12, rotate: -15 },
						pawR: { y: -12, rotate: 15 },
					},
				},
				{
					at: 700,
					eyes: { both: { scaleX: 1.05, scaleY: 1.05, y: -4 } },
					body: {
						y: -2,
						pawL: { y: -6, rotate: -8 },
						pawR: { y: -6, rotate: 8 },
					},
				},
				{ at: 1100, body: { y: 0 } },
			],
		},
	},
	{
		id: "11",
		name: "害羞",
		en: "Shy",
		group: "emotion",
		desc: "小飞机耳耷拉下来，小爪爪微抬捂脸，两颊渐渐泛出红晕。",
		transition: 560,
		pool: ["round", "uneasyA", "droop"],
		poolMs: [3000, 5500],
		blinkMs: [3000, 6000],
		body: {
			rotate: 5,
			breathe: 0.012,
			color: "#FCE7F3",
			blush: 0.92,
			earL: -16,
			earR: 16,
			tail: 0.3,
			tailElev: 0.1,
			mouth: "w",
			pawL: { y: -24, x: 10, rotate: 14 },
			pawR: { y: -24, x: -10, rotate: -14 },
		},
		eyes: { both: { y: 4, lookX: 8, lookY: 3 } },
		anims: [{ type: "sine", target: "eyes", prop: "lookX", amp: 2, period: 2600 }],
		sequence: {
			settle: "hold",
			frames: [
				{ at: 0, body: { color: "#FAF8FF", blush: 0, earL: 0, earR: 0 } },
				{
					at: 1500,
					body: {
						color: "#FCE7F3",
						blush: 0.92,
						earL: -16,
						earR: 16,
						pawL: { y: -24, x: 10, rotate: 14 },
						pawR: { y: -24, x: -10, rotate: -14 },
					},
				},
			],
		},
	},
	{
		id: "12",
		name: "愤怒炸毛",
		en: "Angry",
		group: "emotion",
		desc: "炸毛飞机耳紧紧压平，怒目圆睁，脸色气鼓鼓涨红！",
		transition: 260,
		pool: ["angerMirror", "anger"],
		pair: ["angerMirror", "anger"],
		poolMs: [2200, 3800],
		blinkMs: [3500, 7000],
		body: {
			y: 1,
			breathe: 0.004,
			color: "#FCA5A5",
			earL: -26,
			earR: 26,
			tail: -0.8,
			tailElev: -0.6,
			mouth: "pout",
		},
		eyes: { both: { lookY: -2 } },
		anims: [{ type: "jitter", target: "body", prop: "x", amp: 1.1, speed: 7 }],
		sequence: {
			settle: "hold",
			frames: [
				{ at: 0, body: { color: "#FAF8FF", earL: 0, earR: 0 } },
				{ at: 250, body: { color: "#FCA5A5", earL: -26, earR: 26 } },
			],
		},
	},
	{
		id: "13",
		name: "惊讶呆住",
		en: "Surprised",
		group: "emotion",
		desc: "双耳瞬间立得笔直，眼睛睁大到 1.45 倍定住，整只猫呆住！",
		transition: 180,
		pool: ["wide"],
		poolMs: [2500, 4000],
		blinkMs: [1800, 3500],
		body: {
			y: -4,
			scale: 1.03,
			breathe: 0.006,
			earL: 14,
			earR: -14,
			tail: 0.7,
			tailElev: 0.6,
			mouth: "o",
			pawL: { y: -12 },
			pawR: { y: -12 },
		},
		eyes: { both: { scaleX: 1.14, scaleY: 1.14, y: -2, lookY: -2 } },
		sequence: {
			settle: "base",
			frames: [
				{
					at: 0,
					eyes: { both: { scaleX: 0.92, scaleY: 0.92 } },
					body: { earL: 4, earR: -4 },
				},
				{
					at: 150,
					eyes: { both: { scaleX: 1.45, scaleY: 1.45, y: -4 } },
					body: { y: -7, scale: 1.05, earL: 18, earR: -18, mouth: "o", mouthScale: 1.2 },
				},
				{
					at: 420,
					eyes: { both: { scaleX: 1.22, scaleY: 1.22, y: -3 } },
					body: { earL: 14, earR: -14, mouth: "o" },
				},
			],
		},
	},
	{
		id: "14",
		name: "疑惑不解",
		en: "Puzzled",
		group: "emotion",
		desc: "一耳立起一耳微垂，头歪歪的，眼神充满问号。",
		transition: 420,
		pool: ["uneasyA", "round", "flat"],
		poolMs: [2200, 3800],
		blinkMs: [2800, 5500],
		body: {
			rotate: -8,
			breathe: 0.008,
			earL: 16,
			earR: 20,
			tail: 0.5,
			tailElev: 0.4,
			mouth: "o",
		},
		eyes: {
			left: { y: -4, scaleX: 1.1, scaleY: 1.1 },
			right: { y: 3, scaleX: 0.9, scaleY: 0.9, lookX: 3 },
		},
		anims: [{ type: "sine", target: "body", prop: "rotate", amp: 1.4, period: 3200 }],
	},
	{
		id: "15",
		name: "难过委屈",
		en: "Sad",
		group: "emotion",
		desc: "耳朵无力下垂，眼神可怜巴巴地低垂，缩成一小团。",
		transition: 820,
		pool: ["sad", "droop", "tear"],
		poolMs: [4000, 7000],
		blinkMs: [4000, 8000],
		body: {
			y: 5,
			rotate: -4,
			breathe: 0.007,
			color: "#E5E1F0",
			earL: -18,
			earR: 18,
			tail: -0.2,
			tailElev: -0.7,
			mouth: "pout",
		},
		eyes: { both: { y: 8, scaleX: 0.88, scaleY: 0.88, lookY: 4 } },
		anims: [{ type: "sine", target: "eyes", prop: "y", amp: 1.6, period: 3600 }],
	},
	{
		id: "16",
		name: "失落消沉",
		en: "Gloomy",
		group: "emotion",
		desc: "双耳紧紧缩起来，团成一小颗，静悄悄不作声。",
		transition: 280,
		gaze: false,
		pool: ["droop", "slit"],
		poolMs: [6000, 9000],
		blinkMs: null,
		openness: 0.45,
		body: {
			y: 3,
			breathe: 0.004,
			color: "#DBD6E8",
			earL: -22,
			earR: 22,
			tail: 0,
			tailElev: -0.9,
			mouth: "flat",
		},
		sequence: {
			settle: "hold",
			frames: [
				{ at: 0 },
				{
					at: 1500,
					eyes: { both: { scaleX: 0.6, scaleY: 0.6, open: 0.35, y: 3 } },
					body: { y: 4, scale: 0.97 },
				},
			],
		},
	},
	{
		id: "17",
		name: "撒娇爱意",
		en: "Love",
		group: "emotion",
		desc: "心形猫瞳亮起，小耳朵甜蜜微动，两颊粉扑扑地依偎。",
		transition: 420,
		pool: ["heart"],
		poolMs: [6000, 10000],
		blinkMs: null,
		body: {
			breathe: 0.008,
			blush: 0.95,
			earL: 6,
			earR: -6,
			tail: 0.8,
			tailElev: 0.8,
			mouth: "smile",
		},
		anims: [
			{ type: "pulse", target: "body", prop: "scale", amp: 0.035, period: 1100 },
			{ type: "pulse", target: "eyes", prop: "scale", amp: 0.08, period: 1100, phase: 0.3 },
		],
	},
	{
		id: "18",
		name: "傲娇得意",
		en: "Proud",
		group: "emotion",
		desc: "弯弯笑眼，下巴微扬，两只小耳朵傲娇地点头。",
		transition: 580,
		pool: ["smile", "grin", "round"],
		poolMs: [3500, 6000],
		blinkMs: [3500, 7000],
		antics: true,
		body: { breathe: 0.012, earL: 10, earR: -10, tail: 0.9, tailElev: 0.9, mouth: "smile" },
		eyes: { both: { lookY: -4 } },
		anims: [
			{ type: "sine", target: "eyes", prop: "y", amp: 5, period: 1050 },
			{ type: "sine", target: "body", prop: "y", amp: 1.6, period: 1050, phase: 0.6 },
		],
	},
	{
		id: "19",
		name: "委屈抽泣",
		en: "Pouting / Crying",
		group: "emotion",
		desc: "水汪汪泪眼波动，飞机耳耷拉着微颤，可怜抽搭。",
		transition: 400,
		pool: ["tear", "droop"],
		poolMs: [2400, 4000],
		blinkMs: [2000, 4500],
		body: {
			y: 3,
			rotate: -3,
			color: "#E9E3F3",
			blush: 0.5,
			earL: -20,
			earR: 20,
			tailElev: -0.5,
			mouth: "pout",
		},
		eyes: { both: { lookY: 3, y: 3 } },
		anims: [
			{ type: "jitter", target: "body", prop: "y", amp: 0.8, speed: 12 },
			{ type: "sine", target: "eyes", prop: "lookY", amp: 1.5, period: 2000 },
		],
	},
	{
		id: "20",
		name: "害怕惊吓",
		en: "Scared",
		group: "emotion",
		desc: "双耳紧紧贴头，整只猫缩成小球瑟瑟发抖，瞳孔放大。",
		transition: 160,
		pool: ["wide", "dot"],
		poolMs: [1200, 2400],
		blinkMs: [1500, 3000],
		body: {
			scale: 0.92,
			y: 6,
			earL: -28,
			earR: 28,
			tail: -0.9,
			tailElev: -0.9,
			mouth: "open",
			pawL: { y: 6, rotate: -10 },
			pawR: { y: 6, rotate: 10 },
		},
		anims: [
			{ type: "jitter", target: "body", prop: "x", amp: 2.2, speed: 14 },
			{ type: "jitter", target: "body", prop: "y", amp: 1.5, speed: 12 },
		],
	},
	{
		id: "21",
		name: "俏皮眨眼",
		en: "Winking",
		group: "emotion",
		desc: "一只眼调皮眨动 Wink，小脑袋侧偏，吐舌卖萌。",
		transition: 280,
		pair: ["wink", "round"],
		pool: ["wink", "round"],
		poolMs: [3000, 6000],
		blinkMs: null,
		body: {
			rotate: 8,
			earL: 14,
			earR: -6,
			tail: 0.85,
			tailElev: 0.8,
			blush: 0.65,
			mouth: "tongue",
			pawL: { y: -18, rotate: -18 },
		},
		eyes: { left: { scaleY: 0.9 }, right: { scaleX: 1.08, scaleY: 1.08 } },
		anims: [{ type: "sine", target: "body", prop: "rotate", amp: 2, period: 2200 }],
	},
	{
		id: "22",
		name: "舒适呼噜",
		en: "Purring",
		group: "emotion",
		desc: "眼睛满足眯成一道缝，全身随着舒服呼噜声有节奏地律动。",
		transition: 600,
		pool: ["purr", "smile"],
		poolMs: [4000, 8000],
		blinkMs: null,
		body: {
			breathe: 0.02,
			earL: 4,
			earR: -4,
			tail: 0.95,
			tailElev: 0.8,
			blush: 0.45,
			mouth: "w",
		},
		eyes: { both: { y: 2 } },
		anims: [
			{ type: "pulse", target: "body", prop: "scale", amp: 0.03, period: 800 },
			{ type: "sine", target: "body", prop: "y", amp: 1.8, period: 800 },
		],
	},
	{
		id: "23",
		name: "嫌弃无语",
		en: "Disgusted",
		group: "emotion",
		desc: "大翻白眼，头偏向一边，两只耳朵嫌弃地撇开。",
		transition: 480,
		pool: ["disdain", "uneasyB"],
		poolMs: [3000, 5000],
		blinkMs: [4000, 7000],
		body: { rotate: -9, earL: -14, earR: 22, tail: -0.4, tailElev: -0.3, mouth: "flat" },
		eyes: { both: { lookX: -8, lookY: -7 } },
		anims: [{ type: "sine", target: "eyes", prop: "lookY", amp: 1.2, period: 3200 }],
	},
	{
		id: "24",
		name: "乞求拜托",
		en: "Pleading",
		group: "emotion",
		desc: "水汪汪大眼充满渴望，小爪爪合十拜托，耳朵软糯垂下。",
		transition: 300,
		pool: ["pleading", "sparkle"],
		poolMs: [2000, 3600],
		blinkMs: [2000, 4500],
		body: {
			y: -2,
			breathe: 0.012,
			blush: 0.75,
			earL: -10,
			earR: 10,
			tail: 0.4,
			tailElev: 0.3,
			mouth: "w",
			pawL: { y: -22, x: 12, rotate: 20 },
			pawR: { y: -22, x: -12, rotate: -20 },
		},
		eyes: { both: { lookY: -4, scaleX: 1.15, scaleY: 1.15 } },
		anims: [
			{ type: "pulse", target: "eyes", prop: "scale", amp: 0.06, period: 1200 },
			{ type: "sine", target: "body", prop: "y", amp: 2, period: 1200 },
		],
	},

	// ==================== 3）代理与工作状态 (30-42) ====================
	{
		id: "25",
		name: "思考中",
		en: "Thinking",
		group: "agent",
		desc: "猫瞳在上空巡回推演，头顶有轻灵的思维光环环绕。",
		transition: 480,
		pool: ["round", "angerMirror", "uneasyA", "smile", "uneasyB"],
		poolMs: [2000, 3600],
		blinkMs: [3500, 7000],
		body: {
			rotate: -3,
			breathe: 0.01,
			halo: 1,
			earL: 8,
			earR: 4,
			tailElev: 0.4,
			mouth: "flat",
		},
		eyes: { both: { lookY: -6, y: -2 } },
		anims: [{ type: "sine", target: "eyes", prop: "lookX", amp: 9, period: 2600 }],
	},
	{
		id: "26",
		name: "检索资料",
		en: "Searching",
		group: "agent",
		desc: "双耳紧绷专注，6 组眼环高速翻找扫动，目光左右极速检索。",
		transition: 320,
		pool: ["scan", "uneasyA", "wide", "uneasyB", "dot", "scan"],
		poolMs: [1000, 1800],
		poolSpeed: 10,
		blinkMs: [1600, 4000],
		body: { breathe: 0.006, halo: 1, earL: 12, earR: -12, tailElev: 0.5, mouth: "flat" },
		anims: [{ type: "scan", target: "eyes", prop: "lookX", amp: 11, period: 700 }],
	},
	{
		id: "27",
		name: "出错了",
		en: "Error",
		group: "agent",
		desc: "双耳惊慌抖动，脸色红白急闪，最后定格在警示红。",
		transition: 220,
		pool: ["wide", "round"],
		poolMs: [2000, 3600],
		blinkMs: null,
		body: { rotate: -6, color: "#FCA5A5", earL: -20, earR: 20, tailElev: -0.8, mouth: "pout" },
		eyes: {
			left: { y: -3, rotate: -6 },
			right: { y: 4, rotate: 8 },
		},
		anims: [{ type: "jitter", target: "eyes", prop: "lookX", amp: 1.4, speed: 8, decay: 800 }],
		sequence: {
			settle: "hold",
			frames: [
				{ at: 0, body: { color: "#FCA5A5", rotate: -6 } },
				{ at: 170, body: { color: "#FAF8FF", rotate: -4 } },
				{ at: 340, body: { color: "#FCA5A5", rotate: -7 } },
				{ at: 510, body: { color: "#FAF8FF", rotate: -5 } },
				{ at: 700, body: { color: "#F87171", rotate: -6 } },
			],
		},
	},
	{
		id: "28",
		name: "任务完成",
		en: "Done",
		group: "agent",
		desc: "小耳朵欢呼竖起，自旋甩开 + 漫天撒花庆祝！",
		transition: 240,
		pool: ["smile", "round", "grin"],
		poolMs: [1400, 2600],
		blinkMs: [2200, 4500],
		spin: 1,
		confetti: 0.95,
		body: {
			breathe: 0.012,
			earL: 14,
			earR: -14,
			tail: 1,
			tailElev: 1,
			blush: 0.5,
			mouth: "open",
			pawL: { y: -26, rotate: -20 },
			pawR: { y: -26, rotate: 20 },
		},
		eyes: { both: { y: -3 } },
		sequence: {
			settle: "base",
			frames: [
				{ at: 0, body: { y: 0 } },
				{
					at: 300,
					eyes: { both: { scaleX: 1.1, scaleY: 1.1, y: -5 } },
					body: {
						y: -6,
						pawL: { y: -26, rotate: -20 },
						pawR: { y: -26, rotate: 20 },
					},
				},
				{
					at: 700,
					eyes: { both: { scaleX: 1.05, scaleY: 1.05, y: -4 } },
					body: {
						y: -2,
						pawL: { y: -12, rotate: -10 },
						pawR: { y: -12, rotate: 10 },
					},
				},
				{ at: 1100, body: { y: 0 } },
			],
		},
	},
	{
		id: "29",
		name: "拒绝受限",
		en: "Refusing",
		group: "agent",
		desc: "飞机耳坚定下压，小脑袋连续左右摇头拒绝指令。",
		transition: 380,
		pool: ["uneasyA", "round", "uneasyB"],
		poolMs: [2600, 4500],
		blinkMs: [4500, 8000],
		openness: 0.6,
		body: {
			y: 2,
			rotate: -2,
			color: "#F1EDF7",
			earL: -20,
			earR: 20,
			tailElev: -0.4,
			mouth: "flat",
		},
		eyes: { both: { lookY: 3, y: 2 } },
		sequence: {
			settle: "base",
			frames: [
				{ at: 0, body: { x: 0, earL: -10, earR: 10 } },
				{ at: 130, body: { x: -9, rotate: -6, earL: -24, earR: 14 } },
				{ at: 300, body: { x: 8, rotate: 2, earL: -12, earR: 24 } },
				{ at: 470, body: { x: -6, rotate: -5, earL: -22, earR: 16 } },
				{ at: 630, body: { x: 4, rotate: 0, earL: -14, earR: 20 } },
				{ at: 800, body: { x: 0, rotate: -2, earL: -18, earR: 18 } },
			],
		},
	},
	{
		id: "30",
		name: "正在回复",
		en: "Replying",
		group: "agent",
		desc: "扫读猫瞳轮换，耳朵随流式输出节奏轻微点动。",
		transition: 360,
		pool: ["scan", "round"],
		poolMs: [4000, 8000],
		blinkMs: null,
		body: {
			breathe: 0.008,
			earL: 4,
			earR: -4,
			tail: 0.4,
			tailElev: 0.5,
			mouth: "w",
			pawL: { y: -4 },
			pawR: { y: -4 },
		},
		eyes: { both: { y: -2 } },
		anims: [
			{ type: "pulse", target: "eyes", prop: "scale", amp: 0.1, period: 680 },
			{ type: "sine", target: "body", prop: "y", amp: 1.2, period: 680 },
		],
	},
	{
		id: "31",
		name: "网络加载",
		en: "Loading",
		group: "agent",
		desc: "双耳一前一后轻动，双眼交替眨动同步等待信号。",
		transition: 380,
		pool: ["round", "flat"],
		poolMs: [6000, 10000],
		blinkMs: null,
		body: { breathe: 0.008, earL: 6, earR: 6, tailElev: 0.3, mouth: "o", mouthScale: 0.9 },
		anims: [
			{ type: "blink", target: "left", prop: "open", period: 1600, dur: 700 },
			{ type: "blink", target: "right", prop: "open", period: 1600, dur: 700, phaseMs: 800 },
			{ type: "sine", target: "eyes", prop: "lookX", amp: 2, period: 2400 },
		],
	},
	{
		id: "32",
		name: "翻检记忆",
		en: "Recalling",
		group: "agent",
		desc: "目光漂向左上方翻检上下文记忆，尾巴轻缓摇点。",
		transition: 780,
		pool: ["round", "flat", "droop"],
		poolMs: [4000, 8000],
		blinkMs: null,
		body: {
			rotate: -3,
			breathe: 0.009,
			earL: 8,
			earR: 2,
			tail: 0.3,
			tailElev: 0.4,
			mouth: "w",
		},
		eyes: { both: { lookY: -9, lookX: -4, y: -3 } },
		anims: [{ type: "sine", target: "eyes", prop: "lookY", amp: 2.4, period: 4000 }],
	},
	{
		id: "33",
		name: "接收确认",
		en: "Acknowledged",
		group: "agent",
		desc: "耳朵利落一竖，轻轻眨眼点头，确认收到指令。",
		transition: 220,
		pool: ["smile", "round"],
		poolMs: [4000, 8000],
		blinkMs: null,
		body: { breathe: 0.008, earL: 6, earR: -6, tailElev: 0.6, mouth: "smile" },
		sequence: {
			settle: "base",
			frames: [
				{ at: 0 },
				{ at: 100, eyes: { both: { open: 0.1 } }, body: { earL: -4, earR: 4 } },
				{
					at: 280,
					eyes: { both: { open: 1, scaleX: 1.12, scaleY: 1.12, y: -2 } },
					body: { y: -3, earL: 10, earR: -10 },
				},
				{ at: 700, eyes: { both: { open: 1 } }, body: { y: 0, earL: 0, earR: 0 } },
			],
		},
	},
	{
		id: "34",
		name: "忙碌处理",
		en: "Crunching",
		group: "agent",
		desc: "专注眼环微缩，目光在小范围内高效循环往复处理。",
		transition: 360,
		pool: ["scan", "round", "flat"],
		poolMs: [1800, 3200],
		blinkMs: [2800, 5500],
		body: { breathe: 0.008, earL: 6, earR: -6, tailElev: 0.6, mouth: "w" },
		eyes: {
			left: { x: 3 },
			right: { x: -3 },
		},
		anims: [
			{ type: "sine", target: "eyes", prop: "lookX", amp: 6, period: 1200 },
			{ type: "sine", target: "eyes", prop: "lookY", amp: 4, period: 900, phase: 0.8 },
		],
	},
	{
		id: "35",
		name: "狂欢派对",
		en: "Party",
		group: "agent",
		desc: "星星眼亮起，整圈自旋 + 漫天撒花，开启高能派对时刻！",
		transition: 200,
		pool: ["sparkle", "grin"],
		poolMs: [1000, 2000],
		blinkMs: null,
		spin: 2,
		confetti: 1,
		body: {
			breathe: 0.015,
			earL: 16,
			earR: -16,
			tail: 1,
			tailElev: 1,
			blush: 0.85,
			mouth: "open",
			pawL: { y: -24, rotate: -15 },
			pawR: { y: -24, rotate: 15 },
		},
		eyes: { both: { y: -3 } },
		anims: [{ type: "pulse", target: "body", prop: "scale", amp: 0.05, period: 600 }],
	},
	{
		id: "36",
		name: "警戒巡视",
		en: "Patrolling",
		group: "agent",
		desc: "双耳雷达般敏锐竖起，目光在大广角范围内左右巡视。",
		transition: 400,
		pool: ["wide", "round", "scan"],
		poolMs: [2500, 4500],
		blinkMs: [3000, 6000],
		body: { breathe: 0.008, earL: 14, earR: -14, tail: 0.7, tailElev: 0.7, mouth: "flat" },
		anims: [{ type: "scan", target: "eyes", prop: "lookX", amp: 14, period: 3200 }],
	},
	{
		id: "37",
		name: "警觉警戒",
		en: "Alert",
		group: "agent",
		desc: "双耳笔直坚挺，身体紧绷微提，全神贯注进入戒备状态。",
		transition: 180,
		pool: ["wide", "anger"],
		poolMs: [2000, 3600],
		blinkMs: [2000, 4000],
		body: {
			y: -2,
			scale: 1.02,
			breathe: 0.005,
			earL: 18,
			earR: -18,
			tail: 0.9,
			tailElev: 0.8,
			mouth: "pout",
		},
		eyes: { both: { scaleX: 1.1, scaleY: 1.1, y: -2 } },
		anims: [{ type: "pulse", target: "body", prop: "scale", amp: 0.02, period: 1000 }],
	},
];

export const EMOTION_MAP: ReadonlyMap<string, EmotionDef> = new Map(EMOTIONS.map((e) => [e.id, e]));

export const DEFAULT_EMOTION_ID = "00";
