/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeLabRouteImport } from './routes/theme-lab'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AnnouncementLabRouteImport } from './routes/announcement-lab'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as BlogArchiveRouteImport } from './routes/blog/archive'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMcpRouteImport } from './routes/admin.mcp'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminEmojisRouteImport } from './routes/admin.emojis'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const ThemeLabRoute = ThemeLabRouteImport.update({
  id: '/theme-lab',
  path: '/theme-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementLabRoute = AnnouncementLabRouteImport.update({
  id: '/announcement-lab',
  path: '/announcement-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArchiveRoute = BlogArchiveRouteImport.update({
  id: '/blog/archive',
  path: '/blog/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/announcements/$id',
  path: '/announcements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMcpRoute = AdminMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmojisRoute = AdminEmojisRouteImport.update({
  id: '/emojis',
  path: '/emojis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcement-lab': typeof AnnouncementLabRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/theme-lab': typeof ThemeLabRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/emojis': typeof AdminEmojisRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mcp': typeof AdminMcpRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/archive': typeof BlogArchiveRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement-lab': typeof AnnouncementLabRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/theme-lab': typeof ThemeLabRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/emojis': typeof AdminEmojisRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mcp': typeof AdminMcpRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/archive': typeof BlogArchiveRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcement-lab': typeof AnnouncementLabRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/theme-lab': typeof ThemeLabRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/emojis': typeof AdminEmojisRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mcp': typeof AdminMcpRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/archive': typeof BlogArchiveRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcement-lab'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/theme-lab'
    | '/admin/announcements'
    | '/admin/comments'
    | '/admin/emojis'
    | '/admin/logs'
    | '/admin/mcp'
    | '/admin/media'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/tags'
    | '/admin/users'
    | '/announcements/$id'
    | '/blog/$slug'
    | '/blog/archive'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/profile/'
    | '/projects/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/auth/github/callback'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcement-lab'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/theme-lab'
    | '/admin/announcements'
    | '/admin/comments'
    | '/admin/emojis'
    | '/admin/logs'
    | '/admin/mcp'
    | '/admin/media'
    | '/admin/permissions'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/tags'
    | '/admin/users'
    | '/announcements/$id'
    | '/blog/$slug'
    | '/blog/archive'
    | '/about'
    | '/admin'
    | '/blog'
    | '/profile'
    | '/projects'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/auth/github/callback'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcement-lab'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/theme-lab'
    | '/admin/announcements'
    | '/admin/comments'
    | '/admin/emojis'
    | '/admin/logs'
    | '/admin/mcp'
    | '/admin/media'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/tags'
    | '/admin/users'
    | '/announcements/$id'
    | '/blog/$slug'
    | '/blog/archive'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/profile/'
    | '/projects/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/auth/github/callback'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementLabRoute: typeof AnnouncementLabRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ThemeLabRoute: typeof ThemeLabRoute
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogArchiveRoute: typeof BlogArchiveRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-lab': {
      id: '/theme-lab'
      path: '/theme-lab'
      fullPath: '/theme-lab'
      preLoaderRoute: typeof ThemeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement-lab': {
      id: '/announcement-lab'
      path: '/announcement-lab'
      fullPath: '/announcement-lab'
      preLoaderRoute: typeof AnnouncementLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/archive': {
      id: '/blog/archive'
      path: '/blog/archive'
      fullPath: '/blog/archive'
      preLoaderRoute: typeof BlogArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mcp': {
      id: '/admin/mcp'
      path: '/mcp'
      fullPath: '/admin/mcp'
      preLoaderRoute: typeof AdminMcpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emojis': {
      id: '/admin/emojis'
      path: '/emojis'
      fullPath: '/admin/emojis'
      preLoaderRoute: typeof AdminEmojisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminEmojisRoute: typeof AdminEmojisRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMcpRoute: typeof AdminMcpRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminEmojisRoute: AdminEmojisRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMcpRoute: AdminMcpRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementLabRoute: AnnouncementLabRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ThemeLabRoute: ThemeLabRoute,
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogArchiveRoute: BlogArchiveRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
