/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TweetsIndexRouteImport } from './routes/tweets/index'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as GalleriesIndexRouteImport } from './routes/galleries.index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as UsersUsernameRouteImport } from './routes/users/$username'
import { Route as TweetsIdRouteImport } from './routes/tweets/$id'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as LabThemeRouteImport } from './routes/lab.theme'
import { Route as LabSeriesRouteImport } from './routes/lab.series'
import { Route as LabNavRouteImport } from './routes/lab.nav'
import { Route as LabMascotRouteImport } from './routes/lab.mascot'
import { Route as LabGalleryRouteImport } from './routes/lab.gallery'
import { Route as LabFriendsRouteImport } from './routes/lab.friends'
import { Route as LabBlogRouteImport } from './routes/lab.blog'
import { Route as LabAnnouncementRouteImport } from './routes/lab.announcement'
import { Route as GalleriesNewRouteImport } from './routes/galleries.new'
import { Route as GalleriesIdRouteImport } from './routes/galleries.$id'
import { Route as BlogArchiveRouteImport } from './routes/blog/archive'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeriesRouteImport } from './routes/admin.series'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMcpRouteImport } from './routes/admin.mcp'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminFriendLinksRouteImport } from './routes/admin.friend-links'
import { Route as AdminEmojisRouteImport } from './routes/admin.emojis'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminSeriesIndexRouteImport } from './routes/admin.series.index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as TweetsTopicsTagRouteImport } from './routes/tweets/topics/$tag'
import { Route as GalleriesIdEditRouteImport } from './routes/galleries.$id_.edit'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'
import { Route as AdminSettingsProfileRouteImport } from './routes/admin.settings.profile'
import { Route as AdminSettingsLlmRouteImport } from './routes/admin.settings.llm'
import { Route as AdminSettingsGithubRouteImport } from './routes/admin.settings.github'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin.settings.general'
import { Route as AdminSettingsCodeRunnerRouteImport } from './routes/admin.settings.code-runner'
import { Route as AdminSettingsAuthRouteImport } from './routes/admin.settings.auth'
import { Route as AdminSettingsAboutRouteImport } from './routes/admin.settings.about'
import { Route as AdminSeriesIdRouteImport } from './routes/admin.series.$id'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TweetsIndexRoute = TweetsIndexRouteImport.update({
  id: '/tweets/',
  path: '/tweets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIndexRoute = GalleriesIndexRouteImport.update({
  id: '/galleries/',
  path: '/galleries/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRoute = UsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TweetsIdRoute = TweetsIdRouteImport.update({
  id: '/tweets/$id',
  path: '/tweets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LabThemeRoute = LabThemeRouteImport.update({
  id: '/lab/theme',
  path: '/lab/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSeriesRoute = LabSeriesRouteImport.update({
  id: '/lab/series',
  path: '/lab/series',
  getParentRoute: () => rootRouteImport,
} as any)
const LabNavRoute = LabNavRouteImport.update({
  id: '/lab/nav',
  path: '/lab/nav',
  getParentRoute: () => rootRouteImport,
} as any)
const LabMascotRoute = LabMascotRouteImport.update({
  id: '/lab/mascot',
  path: '/lab/mascot',
  getParentRoute: () => rootRouteImport,
} as any)
const LabGalleryRoute = LabGalleryRouteImport.update({
  id: '/lab/gallery',
  path: '/lab/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LabFriendsRoute = LabFriendsRouteImport.update({
  id: '/lab/friends',
  path: '/lab/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBlogRoute = LabBlogRouteImport.update({
  id: '/lab/blog',
  path: '/lab/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAnnouncementRoute = LabAnnouncementRouteImport.update({
  id: '/lab/announcement',
  path: '/lab/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesNewRoute = GalleriesNewRouteImport.update({
  id: '/galleries/new',
  path: '/galleries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIdRoute = GalleriesIdRouteImport.update({
  id: '/galleries/$id',
  path: '/galleries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArchiveRoute = BlogArchiveRouteImport.update({
  id: '/blog/archive',
  path: '/blog/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/announcements/$id',
  path: '/announcements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeriesRoute = AdminSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMcpRoute = AdminMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFriendLinksRoute = AdminFriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmojisRoute = AdminEmojisRouteImport.update({
  id: '/emojis',
  path: '/emojis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeriesIndexRoute = AdminSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSeriesRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const TweetsTopicsTagRoute = TweetsTopicsTagRouteImport.update({
  id: '/tweets/topics/$tag',
  path: '/tweets/topics/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIdEditRoute = GalleriesIdEditRouteImport.update({
  id: '/galleries/$id_/edit',
  path: '/galleries/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsLlmRoute = AdminSettingsLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsGithubRoute = AdminSettingsGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCodeRunnerRoute = AdminSettingsCodeRunnerRouteImport.update({
  id: '/code-runner',
  path: '/code-runner',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAuthRoute = AdminSettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAboutRoute = AdminSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSeriesIdRoute = AdminSeriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSeriesRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/emojis': typeof AdminEmojisRoute
  '/admin/friend-links': typeof AdminFriendLinksRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mcp': typeof AdminMcpRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/series': typeof AdminSeriesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/archive': typeof BlogArchiveRoute
  '/galleries/$id': typeof GalleriesIdRoute
  '/galleries/new': typeof GalleriesNewRoute
  '/lab/announcement': typeof LabAnnouncementRoute
  '/lab/blog': typeof LabBlogRoute
  '/lab/friends': typeof LabFriendsRoute
  '/lab/gallery': typeof LabGalleryRoute
  '/lab/mascot': typeof LabMascotRoute
  '/lab/nav': typeof LabNavRoute
  '/lab/series': typeof LabSeriesRoute
  '/lab/theme': typeof LabThemeRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/tweets/$id': typeof TweetsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/galleries/': typeof GalleriesIndexRoute
  '/lab/': typeof LabIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/tweets/': typeof TweetsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/auth': typeof AdminSettingsAuthRoute
  '/admin/settings/code-runner': typeof AdminSettingsCodeRunnerRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/github': typeof AdminSettingsGithubRoute
  '/admin/settings/llm': typeof AdminSettingsLlmRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/galleries/$id/edit': typeof GalleriesIdEditRoute
  '/tweets/topics/$tag': typeof TweetsTopicsTagRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/series/': typeof AdminSeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/emojis': typeof AdminEmojisRoute
  '/admin/friend-links': typeof AdminFriendLinksRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mcp': typeof AdminMcpRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/archive': typeof BlogArchiveRoute
  '/galleries/$id': typeof GalleriesIdRoute
  '/galleries/new': typeof GalleriesNewRoute
  '/lab/announcement': typeof LabAnnouncementRoute
  '/lab/blog': typeof LabBlogRoute
  '/lab/friends': typeof LabFriendsRoute
  '/lab/gallery': typeof LabGalleryRoute
  '/lab/mascot': typeof LabMascotRoute
  '/lab/nav': typeof LabNavRoute
  '/lab/series': typeof LabSeriesRoute
  '/lab/theme': typeof LabThemeRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/tweets/$id': typeof TweetsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/galleries': typeof GalleriesIndexRoute
  '/lab': typeof LabIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/series': typeof SeriesIndexRoute
  '/tweets': typeof TweetsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/auth': typeof AdminSettingsAuthRoute
  '/admin/settings/code-runner': typeof AdminSettingsCodeRunnerRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/github': typeof AdminSettingsGithubRoute
  '/admin/settings/llm': typeof AdminSettingsLlmRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/galleries/$id/edit': typeof GalleriesIdEditRoute
  '/tweets/topics/$tag': typeof TweetsTopicsTagRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/series': typeof AdminSeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/emojis': typeof AdminEmojisRoute
  '/admin/friend-links': typeof AdminFriendLinksRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mcp': typeof AdminMcpRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/series': typeof AdminSeriesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/archive': typeof BlogArchiveRoute
  '/galleries/$id': typeof GalleriesIdRoute
  '/galleries/new': typeof GalleriesNewRoute
  '/lab/announcement': typeof LabAnnouncementRoute
  '/lab/blog': typeof LabBlogRoute
  '/lab/friends': typeof LabFriendsRoute
  '/lab/gallery': typeof LabGalleryRoute
  '/lab/mascot': typeof LabMascotRoute
  '/lab/nav': typeof LabNavRoute
  '/lab/series': typeof LabSeriesRoute
  '/lab/theme': typeof LabThemeRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/tweets/$id': typeof TweetsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/galleries/': typeof GalleriesIndexRoute
  '/lab/': typeof LabIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/tweets/': typeof TweetsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/auth': typeof AdminSettingsAuthRoute
  '/admin/settings/code-runner': typeof AdminSettingsCodeRunnerRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/github': typeof AdminSettingsGithubRoute
  '/admin/settings/llm': typeof AdminSettingsLlmRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/galleries/$id_/edit': typeof GalleriesIdEditRoute
  '/tweets/topics/$tag': typeof TweetsTopicsTagRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/series/': typeof AdminSeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/chat'
    | '/forgot-password'
    | '/friends'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/comments'
    | '/admin/emojis'
    | '/admin/friend-links'
    | '/admin/logs'
    | '/admin/mcp'
    | '/admin/media'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/series'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/tags'
    | '/admin/users'
    | '/announcements/$id'
    | '/blog/$slug'
    | '/blog/archive'
    | '/galleries/$id'
    | '/galleries/new'
    | '/lab/announcement'
    | '/lab/blog'
    | '/lab/friends'
    | '/lab/gallery'
    | '/lab/mascot'
    | '/lab/nav'
    | '/lab/series'
    | '/lab/theme'
    | '/series/$slug'
    | '/tweets/$id'
    | '/users/$username'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/galleries/'
    | '/lab/'
    | '/profile/'
    | '/projects/'
    | '/series/'
    | '/tweets/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/series/$id'
    | '/admin/settings/about'
    | '/admin/settings/auth'
    | '/admin/settings/code-runner'
    | '/admin/settings/general'
    | '/admin/settings/github'
    | '/admin/settings/llm'
    | '/admin/settings/profile'
    | '/auth/github/callback'
    | '/galleries/$id/edit'
    | '/tweets/topics/$tag'
    | '/admin/posts/'
    | '/admin/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/chat'
    | '/forgot-password'
    | '/friends'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/comments'
    | '/admin/emojis'
    | '/admin/friend-links'
    | '/admin/logs'
    | '/admin/mcp'
    | '/admin/media'
    | '/admin/permissions'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/tags'
    | '/admin/users'
    | '/announcements/$id'
    | '/blog/$slug'
    | '/blog/archive'
    | '/galleries/$id'
    | '/galleries/new'
    | '/lab/announcement'
    | '/lab/blog'
    | '/lab/friends'
    | '/lab/gallery'
    | '/lab/mascot'
    | '/lab/nav'
    | '/lab/series'
    | '/lab/theme'
    | '/series/$slug'
    | '/tweets/$id'
    | '/users/$username'
    | '/about'
    | '/admin'
    | '/blog'
    | '/galleries'
    | '/lab'
    | '/profile'
    | '/projects'
    | '/series'
    | '/tweets'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/series/$id'
    | '/admin/settings/about'
    | '/admin/settings/auth'
    | '/admin/settings/code-runner'
    | '/admin/settings/general'
    | '/admin/settings/github'
    | '/admin/settings/llm'
    | '/admin/settings/profile'
    | '/auth/github/callback'
    | '/galleries/$id/edit'
    | '/tweets/topics/$tag'
    | '/admin/posts'
    | '/admin/series'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/chat'
    | '/forgot-password'
    | '/friends'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/comments'
    | '/admin/emojis'
    | '/admin/friend-links'
    | '/admin/logs'
    | '/admin/mcp'
    | '/admin/media'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/roles'
    | '/admin/series'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/tags'
    | '/admin/users'
    | '/announcements/$id'
    | '/blog/$slug'
    | '/blog/archive'
    | '/galleries/$id'
    | '/galleries/new'
    | '/lab/announcement'
    | '/lab/blog'
    | '/lab/friends'
    | '/lab/gallery'
    | '/lab/mascot'
    | '/lab/nav'
    | '/lab/series'
    | '/lab/theme'
    | '/series/$slug'
    | '/tweets/$id'
    | '/users/$username'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/galleries/'
    | '/lab/'
    | '/profile/'
    | '/projects/'
    | '/series/'
    | '/tweets/'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/series/$id'
    | '/admin/settings/about'
    | '/admin/settings/auth'
    | '/admin/settings/code-runner'
    | '/admin/settings/general'
    | '/admin/settings/github'
    | '/admin/settings/llm'
    | '/admin/settings/profile'
    | '/auth/github/callback'
    | '/galleries/$id_/edit'
    | '/tweets/topics/$tag'
    | '/admin/posts/'
    | '/admin/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ChatRoute: typeof ChatRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogArchiveRoute: typeof BlogArchiveRoute
  GalleriesIdRoute: typeof GalleriesIdRoute
  GalleriesNewRoute: typeof GalleriesNewRoute
  LabAnnouncementRoute: typeof LabAnnouncementRoute
  LabBlogRoute: typeof LabBlogRoute
  LabFriendsRoute: typeof LabFriendsRoute
  LabGalleryRoute: typeof LabGalleryRoute
  LabMascotRoute: typeof LabMascotRoute
  LabNavRoute: typeof LabNavRoute
  LabSeriesRoute: typeof LabSeriesRoute
  LabThemeRoute: typeof LabThemeRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
  TweetsIdRoute: typeof TweetsIdRoute
  UsersUsernameRoute: typeof UsersUsernameRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GalleriesIndexRoute: typeof GalleriesIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  TweetsIndexRoute: typeof TweetsIndexRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
  GalleriesIdEditRoute: typeof GalleriesIdEditRoute
  TweetsTopicsTagRoute: typeof TweetsTopicsTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tweets/': {
      id: '/tweets/'
      path: '/tweets'
      fullPath: '/tweets/'
      preLoaderRoute: typeof TweetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/': {
      id: '/galleries/'
      path: '/galleries'
      fullPath: '/galleries/'
      preLoaderRoute: typeof GalleriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username': {
      id: '/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tweets/$id': {
      id: '/tweets/$id'
      path: '/tweets/$id'
      fullPath: '/tweets/$id'
      preLoaderRoute: typeof TweetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/theme': {
      id: '/lab/theme'
      path: '/lab/theme'
      fullPath: '/lab/theme'
      preLoaderRoute: typeof LabThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/series': {
      id: '/lab/series'
      path: '/lab/series'
      fullPath: '/lab/series'
      preLoaderRoute: typeof LabSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/nav': {
      id: '/lab/nav'
      path: '/lab/nav'
      fullPath: '/lab/nav'
      preLoaderRoute: typeof LabNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/mascot': {
      id: '/lab/mascot'
      path: '/lab/mascot'
      fullPath: '/lab/mascot'
      preLoaderRoute: typeof LabMascotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/gallery': {
      id: '/lab/gallery'
      path: '/lab/gallery'
      fullPath: '/lab/gallery'
      preLoaderRoute: typeof LabGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/friends': {
      id: '/lab/friends'
      path: '/lab/friends'
      fullPath: '/lab/friends'
      preLoaderRoute: typeof LabFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/blog': {
      id: '/lab/blog'
      path: '/lab/blog'
      fullPath: '/lab/blog'
      preLoaderRoute: typeof LabBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/announcement': {
      id: '/lab/announcement'
      path: '/lab/announcement'
      fullPath: '/lab/announcement'
      preLoaderRoute: typeof LabAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/new': {
      id: '/galleries/new'
      path: '/galleries/new'
      fullPath: '/galleries/new'
      preLoaderRoute: typeof GalleriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/$id': {
      id: '/galleries/$id'
      path: '/galleries/$id'
      fullPath: '/galleries/$id'
      preLoaderRoute: typeof GalleriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/archive': {
      id: '/blog/archive'
      path: '/blog/archive'
      fullPath: '/blog/archive'
      preLoaderRoute: typeof BlogArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/series': {
      id: '/admin/series'
      path: '/series'
      fullPath: '/admin/series'
      preLoaderRoute: typeof AdminSeriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mcp': {
      id: '/admin/mcp'
      path: '/mcp'
      fullPath: '/admin/mcp'
      preLoaderRoute: typeof AdminMcpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/friend-links': {
      id: '/admin/friend-links'
      path: '/friend-links'
      fullPath: '/admin/friend-links'
      preLoaderRoute: typeof AdminFriendLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emojis': {
      id: '/admin/emojis'
      path: '/emojis'
      fullPath: '/admin/emojis'
      preLoaderRoute: typeof AdminEmojisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/series/': {
      id: '/admin/series/'
      path: '/'
      fullPath: '/admin/series/'
      preLoaderRoute: typeof AdminSeriesIndexRouteImport
      parentRoute: typeof AdminSeriesRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/tweets/topics/$tag': {
      id: '/tweets/topics/$tag'
      path: '/tweets/topics/$tag'
      fullPath: '/tweets/topics/$tag'
      preLoaderRoute: typeof TweetsTopicsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/$id_/edit': {
      id: '/galleries/$id_/edit'
      path: '/galleries/$id/edit'
      fullPath: '/galleries/$id/edit'
      preLoaderRoute: typeof GalleriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/profile': {
      id: '/admin/settings/profile'
      path: '/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/llm': {
      id: '/admin/settings/llm'
      path: '/llm'
      fullPath: '/admin/settings/llm'
      preLoaderRoute: typeof AdminSettingsLlmRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/github': {
      id: '/admin/settings/github'
      path: '/github'
      fullPath: '/admin/settings/github'
      preLoaderRoute: typeof AdminSettingsGithubRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/code-runner': {
      id: '/admin/settings/code-runner'
      path: '/code-runner'
      fullPath: '/admin/settings/code-runner'
      preLoaderRoute: typeof AdminSettingsCodeRunnerRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/auth': {
      id: '/admin/settings/auth'
      path: '/auth'
      fullPath: '/admin/settings/auth'
      preLoaderRoute: typeof AdminSettingsAuthRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/about': {
      id: '/admin/settings/about'
      path: '/about'
      fullPath: '/admin/settings/about'
      preLoaderRoute: typeof AdminSettingsAboutRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/series/$id': {
      id: '/admin/series/$id'
      path: '/$id'
      fullPath: '/admin/series/$id'
      preLoaderRoute: typeof AdminSeriesIdRouteImport
      parentRoute: typeof AdminSeriesRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminSeriesRouteChildren {
  AdminSeriesIdRoute: typeof AdminSeriesIdRoute
  AdminSeriesIndexRoute: typeof AdminSeriesIndexRoute
}

const AdminSeriesRouteChildren: AdminSeriesRouteChildren = {
  AdminSeriesIdRoute: AdminSeriesIdRoute,
  AdminSeriesIndexRoute: AdminSeriesIndexRoute,
}

const AdminSeriesRouteWithChildren = AdminSeriesRoute._addFileChildren(
  AdminSeriesRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsAboutRoute: typeof AdminSettingsAboutRoute
  AdminSettingsAuthRoute: typeof AdminSettingsAuthRoute
  AdminSettingsCodeRunnerRoute: typeof AdminSettingsCodeRunnerRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsGithubRoute: typeof AdminSettingsGithubRoute
  AdminSettingsLlmRoute: typeof AdminSettingsLlmRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsAboutRoute: AdminSettingsAboutRoute,
  AdminSettingsAuthRoute: AdminSettingsAuthRoute,
  AdminSettingsCodeRunnerRoute: AdminSettingsCodeRunnerRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsGithubRoute: AdminSettingsGithubRoute,
  AdminSettingsLlmRoute: AdminSettingsLlmRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminEmojisRoute: typeof AdminEmojisRoute
  AdminFriendLinksRoute: typeof AdminFriendLinksRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMcpRoute: typeof AdminMcpRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSeriesRoute: typeof AdminSeriesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminEmojisRoute: AdminEmojisRoute,
  AdminFriendLinksRoute: AdminFriendLinksRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMcpRoute: AdminMcpRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSeriesRoute: AdminSeriesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ChatRoute: ChatRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogArchiveRoute: BlogArchiveRoute,
  GalleriesIdRoute: GalleriesIdRoute,
  GalleriesNewRoute: GalleriesNewRoute,
  LabAnnouncementRoute: LabAnnouncementRoute,
  LabBlogRoute: LabBlogRoute,
  LabFriendsRoute: LabFriendsRoute,
  LabGalleryRoute: LabGalleryRoute,
  LabMascotRoute: LabMascotRoute,
  LabNavRoute: LabNavRoute,
  LabSeriesRoute: LabSeriesRoute,
  LabThemeRoute: LabThemeRoute,
  SeriesSlugRoute: SeriesSlugRoute,
  TweetsIdRoute: TweetsIdRoute,
  UsersUsernameRoute: UsersUsernameRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  GalleriesIndexRoute: GalleriesIndexRoute,
  LabIndexRoute: LabIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  TweetsIndexRoute: TweetsIndexRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
  GalleriesIdEditRoute: GalleriesIdEditRoute,
  TweetsTopicsTagRoute: TweetsTopicsTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
